### ISSUE TITLE
NRPE charm needs osplatform in charmhelpers

### ISSUE THREAD

**Issue by sudeephb** [canonical/charm-nrpe#126]
charm-helpers-hooks.yaml does not have osplatform which leads to:

2017-02-19 21:15:36 INFO install Traceback (most recent call last):
2017-02-19 21:15:36 INFO install   File "/var/lib/juju/agents/unit-nrpe-compute-3/charm/hooks/install", line 2, in <module>
2017-02-19 21:15:36 INFO install     import services
2017-02-19 21:15:36 INFO install   File "/var/lib/juju/agents/unit-nrpe-compute-3/charm/hooks/services.py", line 2, in <module>
2017-02-19 21:15:36 INFO install     from charmhelpers.core.services.base import ServiceManager
2017-02-19 21:15:36 INFO install   File "/var/lib/juju/agents/unit-nrpe-compute-3/charm/hooks/charmhelpers/core/services/__init__.py", line 15, in <module>
2017-02-19 21:15:36 INFO install     from .base import *  # NOQA
2017-02-19 21:15:36 INFO install   File "/var/lib/juju/agents/unit-nrpe-compute-3/charm/hooks/charmhelpers/core/services/base.py", line 20, in <module>
2017-02-19 21:15:36 INFO install     from charmhelpers.core import host
2017-02-19 21:15:36 INFO install   File "/var/lib/juju/agents/unit-nrpe-compute-3/charm/hooks/charmhelpers/core/host.py", line 39, in <module>
2017-02-19 21:15:36 INFO install     from charmhelpers.osplatform import get_platform
2017-02-19 21:15:36 INFO install ImportError: No module named 'charmhelpers.osplatform'
2017-02-19 21:15:36 ERROR juju.worker.uniter.operation runhook.go:107 hook "install" failed: exit status 1

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2017-04-07T00:26:15Z
 * owner: [hloeung](https://launchpad.net/~hloeung)
 * assignee: [None](https://launchpad.net/~None)
 
 
 * the launchpad [url](https://bugs.launchpad.net/bugs/1666064)

**Comment by sudeephb** [comment]
(by [hloeung](https://launchpad.net/~hloeung))
Already fixed in commit 19e8b5732c73d759b2a4cc9cd636fb2d1a84fd67
