### ISSUE TITLE
NRPE charm on Juju 1.25 tries to use network-get and fails

### ISSUE THREAD

**Issue by sudeephb** [canonical/charm-nrpe#140]
When attempting to deploy cs:trusty/nrpe-47, the following backtrace is encountered in the upgrade-charm hook.

2018-02-08 03:48:27 INFO upgrade-charm error: unknown setting "private_address"
2018-02-08 03:48:29 INFO upgrade-charm Traceback (most recent call last):
2018-02-08 03:48:29 INFO upgrade-charm   File "/var/lib/juju/agents/unit-nrpe-lxc-46/charm/hooks/charmhelpers/core/hookenv.py", line 929, in inner_translate_exc2
2018-02-08 03:48:29 INFO upgrade-charm     return f(*args, **kwargs)
2018-02-08 03:48:29 INFO upgrade-charm   File "/var/lib/juju/agents/unit-nrpe-lxc-46/charm/hooks/charmhelpers/core/hookenv.py", line 1116, in network_get_primary_address
2018-02-08 03:48:29 INFO upgrade-charm     stderr=subprocess.STDOUT).decode('UTF-8').strip()
2018-02-08 03:48:29 INFO upgrade-charm   File "/usr/lib/python3.4/subprocess.py", line 607, in check_output
2018-02-08 03:48:29 INFO upgrade-charm     with Popen(*popenargs, stdout=PIPE, **kwargs) as process:
2018-02-08 03:48:29 INFO upgrade-charm   File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
2018-02-08 03:48:29 INFO upgrade-charm     restore_signals, start_new_session)
2018-02-08 03:48:29 INFO upgrade-charm   File "/usr/lib/python3.4/subprocess.py", line 1457, in _execute_child
2018-02-08 03:48:29 INFO upgrade-charm     raise child_exception_type(errno_num, err_msg)
2018-02-08 03:48:29 INFO upgrade-charm FileNotFoundError: [Errno 2] No such file or directory: 'network-get'

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2018-02-08T03:53:21Z
 * owner: [ec0](https://launchpad.net/~ec0)
 * assignee: [None](https://launchpad.net/~None)
 
 
 * the launchpad [url](https://bugs.launchpad.net/bugs/1748087)

**Comment by sudeephb** [comment]
(by [ec0](https://launchpad.net/~ec0))
The code in question is actually in charmhelpers, but I have filed the bug here firstly because it impacts the NRPE charm on 1.25 deployments, and secondly because network_get may never work if network-get is not present. Logic in the NRPE charm may need to be addressed.

**Comment by sudeephb** [comment]
(by [ec0](https://launchpad.net/~ec0))
I have raised https://github.com/juju/charm-helpers/issues/112

I have also noticed that on a trusty/1.25 deployment, the line -
hostname = hookenv.unit_get('private_address')
Does not work, complaining of upgrade-charm error: unknown setting "private_address"

So generically, address handling on 1.25 seems to be broken.

**Comment by sudeephb** [comment]
(by [ec0](https://launchpad.net/~ec0))
Opened https://code.launchpad.net/~jhebden/nrpe-charm/+git/nrpe-charm/+merge/337320 to address

**Comment by sudeephb** [comment]
(by [pjdc](https://launchpad.net/~pjdc))
Fix merged and published in cs:~nrpe-charmers/nrpe-39, and released to cs:nrpe (cs:nrpe-48).
