### ISSUE TITLE
general-info-relation-joined ERROR cannot open 5666/tcp (unit "nrpe/65"): conflicts with existing 5666/tcp (unit "nrpe/68")

### ISSUE THREAD

**Issue by sudeephb** [canonical/charm-nrpe#143]
018-07-02 04:06:15 DEBUG general-info-relation-joined ERROR cannot open 5666/tcp (unit "nrpe/65"): conflicts with existing 5666/tcp (unit "nrpe/68")
2018-07-02 04:06:15 DEBUG general-info-relation-joined Traceback (most recent call last):
2018-07-02 04:06:15 DEBUG general-info-relation-joined   File "/var/lib/juju/agents/unit-nrpe-65/charm/hooks/general-info-relation-joined", line 3, in <module>
2018-07-02 04:06:15 DEBUG general-info-relation-joined     services.manage()
2018-07-02 04:06:15 DEBUG general-info-relation-joined   File "/var/lib/juju/agents/unit-nrpe-65/charm/hooks/services.py", line 67, in manage
2018-07-02 04:06:15 DEBUG general-info-relation-joined     manager.manage()
2018-07-02 04:06:15 DEBUG general-info-relation-joined   File "/var/lib/juju/agents/unit-nrpe-65/charm/hooks/charmhelpers/core/services/base.py", line 135, in manage
2018-07-02 04:06:15 DEBUG general-info-relation-joined     self.reconfigure_services()
2018-07-02 04:06:15 DEBUG general-info-relation-joined   File "/var/lib/juju/agents/unit-nrpe-65/charm/hooks/charmhelpers/core/services/base.py", line 192, in reconfigure_services
2018-07-02 04:06:15 DEBUG general-info-relation-joined     manage_ports])
2018-07-02 04:06:15 DEBUG general-info-relation-joined   File "/var/lib/juju/agents/unit-nrpe-65/charm/hooks/charmhelpers/core/services/base.py", line 234, in fire_event
2018-07-02 04:06:15 DEBUG general-info-relation-joined     callback(self, service_name, event_name)
2018-07-02 04:06:15 DEBUG general-info-relation-joined   File "/var/lib/juju/agents/unit-nrpe-65/charm/hooks/charmhelpers/core/services/base.py", line 326, in __call__
2018-07-02 04:06:15 DEBUG general-info-relation-joined     hookenv.open_port(port, protocol)
2018-07-02 04:06:15 DEBUG general-info-relation-joined   File "/var/lib/juju/agents/unit-nrpe-65/charm/hooks/charmhelpers/core/hookenv.py", line 670, in open_port
2018-07-02 04:06:15 DEBUG general-info-relation-joined     _port_op('open-port', port, protocol)
2018-07-02 04:06:15 DEBUG general-info-relation-joined   File "/var/lib/juju/agents/unit-nrpe-65/charm/hooks/charmhelpers/core/hookenv.py", line 660, in _port_op
2018-07-02 04:06:15 DEBUG general-info-relation-joined     subprocess.check_call(_args)
2018-07-02 04:06:15 DEBUG general-info-relation-joined   File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
2018-07-02 04:06:15 DEBUG general-info-relation-joined     raise CalledProcessError(retcode, cmd)
2018-07-02 04:06:15 DEBUG general-info-relation-joined subprocess.CalledProcessError: Command '['open-port', '5666/TCP']' returned non-zero exit status 1
2018-07-02 04:06:15 ERROR juju.worker.uniter.operation runhook.go:114 hook "general-info-relation-joined" failed: exit status 1
2018-07-02 04:06:15 DEBUG juju.worker.uniter.operation executor.go:75 lock released
2018-07-02 04:06:15 INFO juju.worker.uniter resolver.go:102 awaiting error resolution for "relation-joined" hook
2018-07-02 04:06:15 DEBUG juju.worker.uniter agent.go:17 [AGENT-STATUS] error: hook failed: "general-info-relation-joined"

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2018-07-02T21:49:26Z
 * owner: [cgregan](https://launchpad.net/~cgregan)
 * assignee: [None](https://launchpad.net/~None)
 * duplicate of: #141
 
 
 * the launchpad [url](https://bugs.launchpad.net/bugs/1779769)

**Comment by sudeephb** [comment]
(by [cgregan](https://launchpad.net/~cgregan))

**Comment by sudeephb** [comment]
(by [jog](https://launchpad.net/~jog))
Marked this bug a duplicate of a similar issue the solutions QA team ran into caused by a bundle update. The bundle change installed two units of nrpe on the same machine. The solution was to update the bundle to avoid the second unit deploy.
