### ISSUE TITLE
install nrpe charm results in error, unable to find libnagios-plugin-perl

### ISSUE THREAD

**Issue by sudeephb** [canonical/charm-nrpe#156]
Installing cs:nrpe-74 on Bionic, the nrpe unit managed the install hook but the principal unit went into error state with:

2021-09-01 21:02:33 ERROR unit.infra-node/1.juju-log server.go:325 nrpe-external-master:74: Hook error:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-infra-node-1/.venv/lib/python3.6/site-packages/charms/reactive/__init__.py", line 74, in main
    bus.dispatch(restricted=restricted_mode)
  File "/var/lib/juju/agents/unit-infra-node-1/.venv/lib/python3.6/site-packages/charms/reactive/bus.py", line 390, in dispatch
    _invoke(other_handlers)
  File "/var/lib/juju/agents/unit-infra-node-1/.venv/lib/python3.6/site-packages/charms/reactive/bus.py", line 359, in _invoke
    handler.invoke()
  File "/var/lib/juju/agents/unit-infra-node-1/.venv/lib/python3.6/site-packages/charms/reactive/bus.py", line 181, in invoke
    self._action(*args)
  File "/var/lib/juju/agents/unit-infra-node-1/charm/reactive/infra_node.py", line 18, in update_nrpe_config
    fetch.apt_install(['python-dbus', 'libnagios-plugin-perl'], fatal=True)
  File "/var/lib/juju/agents/unit-infra-node-1/.venv/lib/python3.6/site-packages/charmhelpers/fetch/ubuntu.py", line 303, in apt_install
    _run_apt_command(cmd, fatal, quiet=quiet)
  File "/var/lib/juju/agents/unit-infra-node-1/.venv/lib/python3.6/site-packages/charmhelpers/fetch/ubuntu.py", line 807, in _run_apt_command
    quiet=quiet)
  File "/var/lib/juju/agents/unit-infra-node-1/.venv/lib/python3.6/site-packages/charmhelpers/fetch/ubuntu.py", line 781, in _run_with_retries
    result = subprocess.check_call(cmd, env=env, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['apt-get', '--assume-yes', '--option=Dpkg::Options::=--force-confold', 'install', 'python-dbus', 'libnagios-plugin-perl']' returned non-zero exit status 100.

2021-09-01 21:02:33 WARNING unit.infra-node/1.nrpe-external-master-relation-joined logger.go:60 Traceback (most recent call last):
2021-09-01 21:02:33 WARNING unit.infra-node/1.nrpe-external-master-relation-joined logger.go:60   File "/var/lib/juju/agents/unit-infra-node-1/charm/hooks/nrpe-external-master-relation-joined", line 22, in <module>
2021-09-01 21:02:33 WARNING unit.infra-node/1.nrpe-external-master-relation-joined logger.go:60     main()
2021-09-01 21:02:33 WARNING unit.infra-node/1.nrpe-external-master-relation-joined logger.go:60   File "/var/lib/juju/agents/unit-infra-node-1/.venv/lib/python3.6/site-packages/charms/reactive/__init__.py", line 74, in main
2021-09-01 21:02:33 WARNING unit.infra-node/1.nrpe-external-master-relation-joined logger.go:60     bus.dispatch(restricted=restricted_mode)
2021-09-01 21:02:33 WARNING unit.infra-node/1.nrpe-external-master-relation-joined logger.go:60   File "/var/lib/juju/agents/unit-infra-node-1/.venv/lib/python3.6/site-packages/charms/reactive/bus.py", line 390, in dispatch
2021-09-01 21:02:33 WARNING unit.infra-node/1.nrpe-external-master-relation-joined logger.go:60     _invoke(other_handlers)
2021-09-01 21:02:33 WARNING unit.infra-node/1.nrpe-external-master-relation-joined logger.go:60   File "/var/lib/juju/agents/unit-infra-node-1/.venv/lib/python3.6/site-packages/charms/reactive/bus.py", line 359, in _invoke
2021-09-01 21:02:33 WARNING unit.infra-node/1.nrpe-external-master-relation-joined logger.go:60     handler.invoke()
2021-09-01 21:02:33 WARNING unit.infra-node/1.nrpe-external-master-relation-joined logger.go:60   File "/var/lib/juju/agents/unit-infra-node-1/.venv/lib/python3.6/site-packages/charms/reactive/bus.py", line 181, in invoke
2021-09-01 21:02:33 WARNING unit.infra-node/1.nrpe-external-master-relation-joined logger.go:60     self._action(*args)
2021-09-01 21:02:33 WARNING unit.infra-node/1.nrpe-external-master-relation-joined logger.go:60   File "/var/lib/juju/agents/unit-infra-node-1/charm/reactive/infra_node.py", line 18, in update_nrpe_config
2021-09-01 21:02:33 WARNING unit.infra-node/1.nrpe-external-master-relation-joined logger.go:60     fetch.apt_install(['python-dbus', 'libnagios-plugin-perl'], fatal=True)
2021-09-01 21:02:33 WARNING unit.infra-node/1.nrpe-external-master-relation-joined logger.go:60   File "/var/lib/juju/agents/unit-infra-node-1/.venv/lib/python3.6/site-packages/charmhelpers/fetch/ubuntu.py", line 303, in apt_install
2021-09-01 21:02:33 WARNING unit.infra-node/1.nrpe-external-master-relation-joined logger.go:60     _run_apt_command(cmd, fatal, quiet=quiet)
2021-09-01 21:02:33 WARNING unit.infra-node/1.nrpe-external-master-relation-joined logger.go:60   File "/var/lib/juju/agents/unit-infra-node-1/.venv/lib/python3.6/site-packages/charmhelpers/fetch/ubuntu.py", line 807, in _run_apt_command
2021-09-01 21:02:33 WARNING unit.infra-node/1.nrpe-external-master-relation-joined logger.go:60     quiet=quiet)
2021-09-01 21:02:33 WARNING unit.infra-node/1.nrpe-external-master-relation-joined logger.go:60   File "/var/lib/juju/agents/unit-infra-node-1/.venv/lib/python3.6/site-packages/charmhelpers/fetch/ubuntu.py", line 781, in _run_with_retries
2021-09-01 21:02:33 WARNING unit.infra-node/1.nrpe-external-master-relation-joined logger.go:60     result = subprocess.check_call(cmd, env=env, **kwargs)
2021-09-01 21:02:33 WARNING unit.infra-node/1.nrpe-external-master-relation-joined logger.go:60   File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
2021-09-01 21:02:33 WARNING unit.infra-node/1.nrpe-external-master-relation-joined logger.go:60     raise CalledProcessError(retcode, cmd)
2021-09-01 21:02:33 WARNING unit.infra-node/1.nrpe-external-master-relation-joined logger.go:60 subprocess.CalledProcessError: Command '['apt-get', '--assume-yes', '--option=Dpkg::Options::=--force-confold', 'install', 'python-dbus', 'libnagios-plugin-perl']' returned non-zero exit status 100.
2021-09-01 21:02:33 ERROR juju.worker.uniter.operation runhook.go:139 hook "nrpe-external-master-relation-joined" (via explicit, bespoke hook script) failed: exit status 1
2021-09-01 21:02:33 INFO juju.worker.uniter resolver.go:144 awaiting error resolution for "relation-joined" hook

I did manage to install the monitoring-plugins package without issue.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2021-09-01T21:28:59Z
 * owner: [xavpaice](https://launchpad.net/~xavpaice)
 * assignee: [None](https://launchpad.net/~None)
 
 
 * the launchpad [url](https://bugs.launchpad.net/bugs/1942373)

**Comment by sudeephb** [comment]
(by [xavpaice](https://launchpad.net/~xavpaice))
Looking at another Bionic NRPE machine, the package libnagios-plugin-perl isn't even installed, though the relations all completed successfully.  The installation is in infra-node, will change the target for the bug report.

in infra_node.py:

      if CompareHostReleases(_release) <= 'bionic':                                       
          fetch.apt_install(['python-dbus', 'libnagios-plugin-perl'], fatal=True)         
      else:                                                                               
          fetch.apt_install(['python-dbus', 'libmonitoring-plugin-perl']) 

In Bionic, on this host, there's no candidate for that package, but there is libmonitoring-plugin-perl.
