### ISSUE TITLE
install hook fails on containers

### ISSUE THREAD

**Issue by sudeephb** [canonical/charm-nrpe#163]
charm fails to install on containers with the following traceback

unit-nrpe-0: 15:29:02 INFO unit.nrpe/0.juju-log Getting ingress IP address for binding monitors
unit-nrpe-0: 15:29:29 WARNING unit.nrpe/0.install Traceback (most recent call last):
unit-nrpe-0: 15:29:29 WARNING unit.nrpe/0.install   File "/var/lib/juju/agents/unit-nrpe-0/charm/hooks/install", line 4, in <module>
unit-nrpe-0: 15:29:29 WARNING unit.nrpe/0.install     import services
unit-nrpe-0: 15:29:29 WARNING unit.nrpe/0.install   File "/var/lib/juju/agents/unit-nrpe-0/charm/hooks/services.py", line 33, in <module>
unit-nrpe-0: 15:29:29 WARNING unit.nrpe/0.install     nrpe_helpers.NagiosInfo(),
unit-nrpe-0: 15:29:29 WARNING unit.nrpe/0.install   File "/var/lib/juju/agents/unit-nrpe-0/charm/hooks/nrpe_helpers.py", line 368, in __init__
unit-nrpe-0: 15:29:29 WARNING unit.nrpe/0.install     self["nagios_ipaddress"] = get_ingress_address("monitors", external=True)
unit-nrpe-0: 15:29:29 WARNING unit.nrpe/0.install   File "/var/lib/juju/agents/unit-nrpe-0/charm/hooks/nrpe_helpers.py", line 160, in get_ingress_address
unit-nrpe-0: 15:29:29 WARNING unit.nrpe/0.install     network_info = hookenv.network_get(binding)
unit-nrpe-0: 15:29:29 WARNING unit.nrpe/0.install   File "/var/lib/juju/agents/unit-nrpe-0/charm/hooks/charmhelpers/core/hookenv.py", line 1404, in network_get
unit-nrpe-0: 15:29:29 WARNING unit.nrpe/0.install     response = subprocess.check_output(
unit-nrpe-0: 15:29:29 WARNING unit.nrpe/0.install   File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
unit-nrpe-0: 15:29:29 WARNING unit.nrpe/0.install     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
unit-nrpe-0: 15:29:29 WARNING unit.nrpe/0.install   File "/usr/lib/python3.10/subprocess.py", line 524, in run
unit-nrpe-0: 15:29:29 WARNING unit.nrpe/0.install     raise CalledProcessError(retcode, process.args,
unit-nrpe-0: 15:29:29 WARNING unit.nrpe/0.install subprocess.CalledProcessError: Command '['network-get', 'monitors', '--format', 'yaml']' returned non-zero exit status 1.
unit-nrpe-0: 15:29:30 ERROR juju.worker.uniter.operation hook "install" (via explicit, bespoke hook script) failed: exit status 1

When manually run, the command returns the following:
miles@mertkirpici-bastion-focal:~$ juju run --unit nrpe/0 -- network-get monitors --format yaml
ERROR no network config found for binding "monitors"

This is observed in jammy, focal and bionic containers.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2022-11-28T15:38:27Z
 * owner: [mertkirpici](https://launchpad.net/~mertkirpici)
 * assignee: [gabrielcocenza](https://launchpad.net/~gabrielcocenza)
 
 
 * the launchpad [url](https://bugs.launchpad.net/bugs/1998120)

**Comment by sudeephb** [comment]
(by [mertkirpici](https://launchpad.net/~mertkirpici))
