### ISSUE TITLE
nrpe hook fails "nrpe-external-master-relation-joined"

### ISSUE THREAD

**Issue by sudeephb** [canonical/charm-nrpe#166]
In testrun https://solutions.qa.canonical.com/v2/testruns/ffcf3ea8-028c-4fde-88d7-3b00fcf07d66, all the nrpe units on the OpenStack layer fail with:

====
hook failed: "nrpe-external-master-relation-joined"
====

in the debug log we see:

====
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-nrpe-86/charm/hooks/nrpe-external-master-relation-joined", line 6, in <module>
    services.manage()
  File "/var/lib/juju/agents/unit-nrpe-86/charm/hooks/services.py", line 103, in manage
    manager.manage()
  File "/var/lib/juju/agents/unit-nrpe-86/charm/hooks/charmhelpers/core/services/base.py", line 136, in manage
    self.reconfigure_services()
  File "/var/lib/juju/agents/unit-nrpe-86/charm/hooks/charmhelpers/core/services/base.py", line 190, in reconfigure_services
    self.fire_event('data_ready', service_name)
  File "/var/lib/juju/agents/unit-nrpe-86/charm/hooks/charmhelpers/core/services/base.py", line 237, in fire_event
    callback(service_name)
  File "/var/lib/juju/agents/unit-nrpe-86/charm/hooks/nrpe_utils.py", line 213, in update_monitor_relation
    relation_id=rid, relation_settings=monitor_relation.provide_data()
  File "/var/lib/juju/agents/unit-nrpe-86/charm/hooks/nrpe_helpers.py", line 271, in provide_data
    "monitors": self.get_monitors(),
  File "/var/lib/juju/agents/unit-nrpe-86/charm/hooks/nrpe_helpers.py", line 232, in get_monitors
    self.get_principal_monitors(),
  File "/var/lib/juju/agents/unit-nrpe-86/charm/hooks/nrpe_helpers.py", line 213, in get_principal_monitors
    return self.principal_relation.get_monitors()
  File "/var/lib/juju/agents/unit-nrpe-86/charm/hooks/nrpe_helpers.py", line 340, in get_monitors
    monitors.add_monitors(yaml.load(rel["monitors"]), "principal")
TypeError: load() missing 1 required positional argument: 'Loader'
====

Crashdumps and configs can be found here:
https://oil-jenkins.canonical.com/artifacts/ffcf3ea8-028c-4fde-88d7-3b00fcf07d66/index.html

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2023-04-20T15:28:19Z
 * owner: [basdbruijne](https://launchpad.net/~basdbruijne)
 * assignee: [None](https://launchpad.net/~None)
 
 
 * the launchpad [url](https://bugs.launchpad.net/bugs/2017150)

**Comment by sudeephb** [comment]
(by [basdbruijne](https://launchpad.net/~basdbruijne))
This test run is using latest/candidate

**Comment by sudeephb** [comment]
(by [basdbruijne](https://launchpad.net/~basdbruijne))
Switching to latest/stable did not solve this issue. Looking at the juju status output (https://oil-jenkins.canonical.com/job/fce_build/23514//consoleFull towards the bottom), it looks like it depends on the primary application that nrpe is deployed to. I am wondering if there is a change introduced in OpenStack/antelope that interferes with nrpe. If a newer version of python-yaml is installed there then that would indeed uncover this issue.

I am tagging nova-cloud-controller on this bug (even though there are many more charms where this shows up).

**Comment by sudeephb** [comment]
(by [basdbruijne](https://launchpad.net/~basdbruijne))
It looks like this bug was fixed already with https://git.launchpad.net/charm-nrpe/commit/?id=1fbc315993a936ed0f89dc481f1bfa2fa82aec8a. I can't find if it is released already, but I will switch to nrpe latest/edge to try.

**Comment by sudeephb** [comment]
(by [freyes](https://launchpad.net/~freyes))
On Fri, 2023-04-21 at 16:27 +0000, Bas de Bruijne wrote:
> It looks like this bug was fixed already with
> https://git.launchpad.net/charm-
> nrpe/commit/?id=1fbc315993a936ed0f89dc481f1bfa2fa82aec8a. I can't find
> if it is released already, but I will switch to nrpe latest/edge to try.

yes, this fix is available in latest/edge

**Comment by sudeephb** [comment]
(by [eric-chen](https://launchpad.net/~eric-chen))
I push the patch to latest/candidate. You can verify it again. If there is no problem, it's probably we will push it to latest/stable next week.
