### ISSUE TITLE
NRPE does not support 'disco' series

### ISSUE THREAD

**Issue by sudeephb** [canonical/charm-nrpe#19]
This might go better in a 'wishlist' than a bug. The charm does not support yet the disco series, which blocks the testing of a disco-stein bundle for the charm-rabbitmq-server. Here is the traceback of the func test :

DEBUG:runner:2019-08-29 17:44:24  Deploying application nrpe using cs:nrpe-58
DEBUG:runner:2019-08-29 17:44:25 Error deploying application 'nrpe'
DEBUG:runner:2019-08-29 17:44:25 Command (juju deploy -m auto-osci-sv11:admin/auto-osci-sv11 --series disco cs:nrpe-58 nrpe) Output:
DEBUG:runner:
DEBUG:runner: ERROR series "disco" not supported by charm, supported series are: xenial,trusty,artful,bionic. Use --force to deploy the charm anyway.
DEBUG:runner:
DEBUG:runner:2019-08-29 17:44:25 Deployment stopped. run time: 6.58
DEBUG:runner:Traceback (most recent call last):
DEBUG:runner:  File "/tmp/bundletester-u1veI7/rabbitmq-server/tests/gate-basic-disco-stein", line 22, in <module>
DEBUG:runner:    deployment = RmqBasicDeployment(series='disco')
DEBUG:runner:  File "/tmp/bundletester-u1veI7/rabbitmq-server/tests/basic_deployment.py", line 66, in __init__
DEBUG:runner:    self._deploy()
DEBUG:runner:  File "/tmp/tmp.CuR2YNAF9s/func27/local/lib/python2.7/site-packages/charmhelpers/contrib/amulet/deployment.py", line 85, in _deploy
DEBUG:runner:    self.d.setup(timeout=timeout)
DEBUG:runner:  File "/tmp/tmp.CuR2YNAF9s/func27/local/lib/python2.7/site-packages/amulet/deployer.py", line 714, in setup
DEBUG:runner:    subprocess.check_call(shlex.split(cmd))
DEBUG:runner:  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
DEBUG:runner:    raise CalledProcessError(retcode, cmd)
DEBUG:runner:subprocess.CalledProcessError: Command '['juju-deployer', '-W', '-c', '/tmp/amulet-juju-deployer-ypSKIo/deployer-schema.json', '-e', 'auto-osci-sv11:admin/auto-osci-sv11', '-t', '5500', 'auto-osci-sv11:admin/auto-osci-sv11']' returned non-zero exit status 1
DEBUG:runner:Exit Code: 1
DEBUG:bundletester.utils:Updating JUJU_MODEL: "auto-osci-sv11:admin/auto-osci-sv11" -> ""
DEBUG:bundletester.fetchers:git rev-parse HEAD: 7ba1da0d30e5ef1defa2f8871980a5a16605169f

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2019-08-29T21:15:22Z
 * owner: [camille.rodriguez](https://launchpad.net/~camille.rodriguez)
 * assignee: [1chb1n](https://launchpad.net/~1chb1n)
 
 
 * the launchpad [url](https://bugs.launchpad.net/bugs/1841998)

**Comment by sudeephb** [comment]
(by [1chb1n](https://launchpad.net/~1chb1n))
https://code.launchpad.net/~1chb1n/nrpe-charm/+git/nrpe-charm/+merge/372299
