### ISSUE TITLE
rsync dependency conflicts with 20.04 CIS hardening

### ISSUE THREAD

**Issue by sudeephb** [canonical/charm-nrpe#26]
Hi team,

I am currently using latest stable NRPE charm on a CIS harderned system following:
https://ubuntu.com/security/certifications/docs/usg/cis/compliance

I can see the following rule is applied by CIS:
Title   Uninstall rsync Package
Rule    package_rsync_removed

And once deploying NRPE on this hardened system, I get:
2022-03-07 18:38:35 INFO unit.nrpe-host/5.juju-log server.go:327 Making dir /etc/rsync-juju.d root:root 755
2022-03-07 18:38:35 INFO unit.nrpe-host/5.juju-log server.go:327 /usr/bin/rsync -r --executability /var/lib/juju/agents/unit-nrpe-host-5/charm/files/plugins /usr/local/lib/nagios/
2022-03-07 18:38:35 WARNING unit.nrpe-host/5.install logger.go:60 Traceback (most recent call last):
2022-03-07 18:38:35 WARNING unit.nrpe-host/5.install logger.go:60   File "/var/lib/juju/agents/unit-nrpe-host-5/charm/hooks/install", line 6, in <module>
2022-03-07 18:38:35 WARNING unit.nrpe-host/5.install logger.go:60     services.manage()
2022-03-07 18:38:35 WARNING unit.nrpe-host/5.install logger.go:60   File "/var/lib/juju/agents/unit-nrpe-host-5/charm/hooks/services.py", line 88, in manage
2022-03-07 18:38:35 WARNING unit.nrpe-host/5.install logger.go:60     manager.manage()
2022-03-07 18:38:35 WARNING unit.nrpe-host/5.install logger.go:60   File "/var/lib/juju/agents/unit-nrpe-host-5/charm/hooks/charmhelpers/core/services/base.py", line 137, in manage
2022-03-07 18:38:35 WARNING unit.nrpe-host/5.install logger.go:60     self.reconfigure_services()
2022-03-07 18:38:35 WARNING unit.nrpe-host/5.install logger.go:60   File "/var/lib/juju/agents/unit-nrpe-host-5/charm/hooks/charmhelpers/core/services/base.py", line 194, in reconfigure_services
2022-03-07 18:38:35 WARNING unit.nrpe-host/5.install logger.go:60     self.fire_event('data_ready', service_name)
2022-03-07 18:38:35 WARNING unit.nrpe-host/5.install logger.go:60   File "/var/lib/juju/agents/unit-nrpe-host-5/charm/hooks/charmhelpers/core/services/base.py", line 241, in fire_event
2022-03-07 18:38:35 WARNING unit.nrpe-host/5.install logger.go:60     callback(service_name)
2022-03-07 18:38:35 WARNING unit.nrpe-host/5.install logger.go:60   File "/var/lib/juju/agents/unit-nrpe-host-5/charm/hooks/nrpe_utils.py", line 106, in install_charm_files
2022-03-07 18:38:35 WARNING unit.nrpe-host/5.install logger.go:60     host.rsync(charm_plugin_dir, "/usr/local/lib/nagios/", options=["--executability"])
2022-03-07 18:38:35 WARNING unit.nrpe-host/5.install logger.go:60   File "/var/lib/juju/agents/unit-nrpe-host-5/charm/hooks/charmhelpers/core/host.py", line 510, in rsync
2022-03-07 18:38:35 WARNING unit.nrpe-host/5.install logger.go:60     return subprocess.check_output(cmd, stderr=subprocess.STDOUT).decode('UTF-8').strip()
2022-03-07 18:38:35 WARNING unit.nrpe-host/5.install logger.go:60   File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
2022-03-07 18:38:35 WARNING unit.nrpe-host/5.install logger.go:60     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
2022-03-07 18:38:35 WARNING unit.nrpe-host/5.install logger.go:60   File "/usr/lib/python3.8/subprocess.py", line 493, in run
2022-03-07 18:38:35 WARNING unit.nrpe-host/5.install logger.go:60     with Popen(*popenargs, **kwargs) as process:
2022-03-07 18:38:35 WARNING unit.nrpe-host/5.install logger.go:60   File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
2022-03-07 18:38:35 WARNING unit.nrpe-host/5.install logger.go:60     self._execute_child(args, executable, preexec_fn, close_fds,
2022-03-07 18:38:35 WARNING unit.nrpe-host/5.install logger.go:60   File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
2022-03-07 18:38:35 WARNING unit.nrpe-host/5.install logger.go:60     raise child_exception_type(errno_num, err_msg, err_filename)
2022-03-07 18:38:35 WARNING unit.nrpe-host/5.install logger.go:60 FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/rsync'
2022-03-07 18:38:35 ERROR juju.worker.uniter.operation runhook.go:146 hook "install" (via explicit, bespoke hook script) failed: exit status 1
2022-03-07 18:38:35 INFO juju.worker.uniter resolver.go:150 awaiting error resolution for "install" hook

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2022-03-07T19:37:47Z
 * owner: [pguimaraes](https://launchpad.net/~pguimaraes)
 * assignee: [xavpaice](https://launchpad.net/~xavpaice)
 
 
 * the launchpad [url](https://bugs.launchpad.net/bugs/1964027)

**Comment by sudeephb** [comment]
(by [xavpaice](https://launchpad.net/~xavpaice))
export_nagios_definitions defaults to False, but if nagios_master is set, rsync will still be installed.

In install_charm_files() rsync files are copied regardless of settings, we should make that conditional on export_nagios_definitions being true.

I also think that since using nagios_master is helpful even when we're not using rsync, we should split the condition to _require_ export_nagios_definitions to be true before installing/configuring rsync.

**Comment by sudeephb** [comment]
(by [xavpaice](https://launchpad.net/~xavpaice))
subscribed field-critical - this bug is blocking deployment of the application in an active field engagement.
