### ISSUE TITLE
latest charm (cs:nrpe-14) does not install

### ISSUE THREAD

**Issue by sudeephb** [canonical/charm-nrpe#4]
Hello there,

The latest NRPE charm is not installing and producing the following error.
Reverting back to nrpe-13 is resolving the issue.

----
DEBUG juju.worker.uniter.operation executor.go:100 executing operation "run install hook"
DEBUG juju.worker.uniter agent.go:17 [AGENT-STATUS] executing: running install hook
INFO install Traceback (most recent call last):
INFO install   File "/var/lib/juju/agents/unit-nrpe-0/charm/hooks/install", line 2, in <module>
INFO install     import services
INFO install   File "/var/lib/juju/agents/unit-nrpe-0/charm/hooks/services.py", line 1, in <module>
INFO install     from charmhelpers.core import hookenv
INFO install ImportError: No module named 'charmhelpers.core'
ERROR juju.worker.uniter.operation runhook.go:107 hook "install" failed: exit status 1
DEBUG juju.worker.uniter.operation executor.go:84 lock released
INFO juju.worker.uniter resolver.go:100 awaiting error resolution for "install" hook
DEBUG juju.worker.uniter agent.go:17 [AGENT-STATUS] error: hook failed: "install"
DEBUG juju.worker.uniter.remotestate watcher.go:434 retry hook timer triggered
----

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2017-04-05T07:51:41Z
 * owner: [fairbanks](https://launchpad.net/~fairbanks)
 * assignee: [paulgear](https://launchpad.net/~paulgear)
 
 
 * the launchpad [url](https://bugs.launchpad.net/bugs/1679963)

**Comment by sudeephb** [comment]
(by [fginther](https://launchpad.net/~fginther))
charmhelpers.core is missing from this latest upload (nrpe-14).

**Comment by sudeephb** [comment]
(by [1chb1n](https://launchpad.net/~1chb1n))
The charm artifact (zip) from the charm store @ https://jujucharms.com/nrpe/14 contains no charmhelpers/core dir, despite core being defined in charm-helpers-hooks.yaml as being sync'd.

Master charmhelpers/core dir exists:
https://git.launchpad.net/nrpe-charm/tree/hooks/charmhelpers/core?id=2561575604c01e07a5026d1f42c45258cc67c014

IMO, this charm should have python unit tests added so that synthetic (fast/inexpensive) validation can be performed by developers and reviewers.

**Comment by sudeephb** [comment]
(by [paulgear](https://launchpad.net/~paulgear))
I've just synced charmhelpers again and pushed cs:~nrpe-charmers/nrpe-6 to the candidate channel.  Please test and let me know if it fixes your issues.

**Comment by sudeephb** [comment]
(by [paulgear](https://launchpad.net/~paulgear))
I've tested cs:~nrpe-charmers/nrpe-6 (https://jujucharms.com/nrpe/15) in three different environments, and it has installed/upgraded successfully for me in all of them.

**Comment by sudeephb** [comment]
(by [mthaddon](https://launchpad.net/~mthaddon))
cs:nrpe now points to revision 15, which we've confirmed does install. Please let us know if you have any issues.
