### ISSUE TITLE
does not allow for cidr expression in nagios_master config

### ISSUE THREAD

**Issue by sudeephb** [canonical/charm-nrpe#66]
latest/stable nrpe charm

In the even that nagios and nrpe are within separate models within openstack substrate, nrpe must be exposed.  Also, the nagios unit IP address cannot be predicted.  After deploy the charm allows for setting nagios_master to a cidr (such as 192.168.100.0/24), however if the charm is set to this config at deploy time the following error occurs:

```
2021-08-28 19:11:23 DEBUG juju.worker.uniter.runner runner.go:714 starting jujuc server  {unix **/var/lib/juju/agents/unit-nrpe-0/agent.socket** <nil>}
2021-08-28 19:11:23 WARNING unit.nrpe/0.install logger.go:60 Traceback (most recent call last):
2021-08-28 19:11:23 WARNING unit.nrpe/0.install logger.go:60   File "/var/lib/juju/agents/unit-nrpe-0/charm/hooks/install", line 6, in <module>
2021-08-28 19:11:23 WARNING unit.nrpe/0.install logger.go:60     services.manage()
2021-08-28 19:11:23 WARNING unit.nrpe/0.install logger.go:60   File "/var/lib/juju/agents/unit-nrpe-0/charm/hooks/services.py", line 36, in manage
2021-08-28 19:11:23 WARNING unit.nrpe/0.install logger.go:60     nrpe_helpers.NagiosInfo(),
2021-08-28 19:11:23 WARNING unit.nrpe/0.install logger.go:60   File "/var/lib/juju/agents/unit-nrpe-0/charm/hooks/nrpe_helpers.py", line 297, in __init__
2021-08-28 19:11:23 WARNING unit.nrpe/0.install logger.go:60     s.connect((hookenv.config("nagios_master").split(",")[0], 80))
2021-08-28 19:11:23 WARNING unit.nrpe/0.install logger.go:60 socket.gaierror: [Errno -2] Name or service not known
2021-08-28 19:11:23 ERROR juju.worker.uniter.operation runhook.go:139 hook "install" (via explicit, bespoke hook script) failed: exit status 1
```

A cidr should be allows due to the unpredictability of the internal tenant address of the deployed nagios charm which is in a seperate model, and thus in a different security group.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2021-08-28T19:17:04Z
 * owner: [jhillman](https://launchpad.net/~jhillman)
 * assignee: [None](https://launchpad.net/~None)
 
 
 * the launchpad [url](https://bugs.launchpad.net/bugs/1941958)

**Comment by sudeephb** [comment]
(by [jhillman](https://launchpad.net/~jhillman))
Update:  This issue does not happen when the nagios_address_type is set to public.  If this is intended behavior, then please invalidate this bug.

**Comment by sudeephb** [comment]
(by [eric-chen](https://launchpad.net/~eric-chen))
This charm is under maintenance mode. Only critical bug will be handled.
