### ISSUE TITLE
Can't Handle Unicode Correctly

### ISSUE THREAD

**Issue by sudeephb** [canonical/charm-nrpe#81]
The NRPE charm crashes when receiving unicode data:

    2018-02-24 00:36:35 INFO monitors-relation-changed Traceback (most recent call last):
    2018-02-24 00:36:35 INFO monitors-relation-changed   File "/var/lib/juju/agents/unit-nrpe-47/charm/hooks/monitors-relation-changed", line 3, in <module>
    2018-02-24 00:36:35 INFO monitors-relation-changed     services.manage()
    2018-02-24 00:36:35 INFO monitors-relation-changed   File "/var/lib/juju/agents/unit-nrpe-47/charm/hooks/services.py", line 27, in manage
    2018-02-24 00:36:35 INFO monitors-relation-changed nrpe_helpers.NagiosInfo(),
    2018-02-24 00:36:35 INFO monitors-relation-changed   File "/var/lib/juju/agents/unit-nrpe-47/charm/hooks/nrpe_helpers.py", line 205, in __init__
    2018-02-24 00:36:35 INFO monitors-relation-changed self['nagios_hostname'] = self.principal_relation.nagios_hostname()
    2018-02-24 00:36:35 INFO monitors-relation-changed   File "/var/lib/juju/agents/unit-nrpe-47/charm/hooks/nrpe_helpers.py", line 167, in nagios_hostname
    2018-02-24 00:36:35 INFO monitors-relation-changed     principal_unitname = hookenv.principal_unit()
    2018-02-24 00:36:35 INFO monitors-relation-changed   File "/var/lib/juju/agents/unit-nrpe-47/charm/hooks/charmhelpers/core/hookenv.py", line 220, in principal_unit
    2018-02-24 00:36:35 INFO monitors-relation-changed     md = _metadata_unit(unit)
    2018-02-24 00:36:35 INFO monitors-relation-changed   File "/var/lib/juju/agents/unit-nrpe-47/charm/hooks/charmhelpers/core/hookenv.py", line 520, in _metadata_unit
    2018-02-24 00:36:35 INFO monitors-relation-changed     return yaml.safe_load(md)
    2018-02-24 00:36:35 INFO monitors-relation-changed   File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 94, in safe_load
    2018-02-24 00:36:35 INFO monitors-relation-changed     return load(stream, SafeLoader)
    2018-02-24 00:36:35 INFO monitors-relation-changed   File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 70, in load
    2018-02-24 00:36:35 INFO monitors-relation-changed     loader = Loader(stream)
    2018-02-24 00:36:35 INFO monitors-relation-changed   File "/usr/lib/python3/dist-packages/yaml/loader.py", line 24, in __init__
    2018-02-24 00:36:35 INFO monitors-relation-changed Reader.__init__(self, stream)
    2018-02-24 00:36:35 INFO monitors-relation-changed   File "/usr/lib/python3/dist-packages/yaml/reader.py", line 85, in __init__
    2018-02-24 00:36:35 INFO monitors-relation-changed self.determine_encoding()
    2018-02-24 00:36:35 INFO monitors-relation-changed   File "/usr/lib/python3/dist-packages/yaml/reader.py", line 124, in determine_encoding
    2018-02-24 00:36:35 INFO monitors-relation-changed     self.update_raw()
    2018-02-24 00:36:35 INFO monitors-relation-changed   File "/usr/lib/python3/dist-packages/yaml/reader.py", line 178, in update_raw
    2018-02-24 00:36:35 INFO monitors-relation-changed     data = self.stream.read(size)
    2018-02-24 00:36:35 INFO monitors-relation-changed   File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
    2018-02-24 00:36:35 INFO monitors-relation-changed     return codecs.ascii_decode(input, self.errors)[0]
    2018-02-24 00:36:35 INFO monitors-relation-changed UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 311: ordinal not in range(128)
    2018-02-24 00:36:35 ERROR juju.worker.uniter.operation runhook.go:107 hook "monitors-relation-changed" failed: exit status 1

- I believed this to be a unicode python bug such as the one described in:

    https://bugs.launchpad.net/charms/+source/ceph-radosgw/+bug/1542074

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2018-02-28T02:59:56Z
 * owner: [craige](https://launchpad.net/~craige)
 * assignee: [None](https://launchpad.net/~None)
 
 
 * the launchpad [url](https://bugs.launchpad.net/bugs/1752222)

**Comment by sudeephb** [comment]
(by [hloeung](https://launchpad.net/~hloeung))
This is probably similar to LP: #1721200

**Comment by sudeephb** [comment]
(by [stub](https://launchpad.net/~stub))
Is metadata.yaml in the built charm valid UTF-8? The yaml library is failing to parse it.

It may be triggered by the version of the yaml library installed. nrpe is not a reactive charm, as it is using the python3-yaml deb package version of the library.

**Comment by sudeephb** [comment]
(by [stub](https://launchpad.net/~stub))
(charmhelpers.core.hookenv.principal_unit() is falling back to compatibility code, attempting to to discover the principal unit name by looking at the metadata.yaml of the other cohosted units. So the metadata.yaml triggering this could be the primary charm's or another subordinate).

**Comment by sudeephb** [comment]
(by [xavpaice](https://launchpad.net/~xavpaice))
This needs some further testing to get a reliable reproducer, I suspect it's only an issue when there's non-ascii chars in the data passed over the relation between the subordinate and principal.
